### ISSUE TITLE
yarn.lock: should be gitignored?

### ISSUE THREAD

**Issue by kevinmerckx** [interfacewerk/ng2-stateful-button#2]

**Comment by mochtu** [comment]
Quote from https://yarnpkg.com/en/docs/migrating-from-npm

> When you run either yarn or yarn add <package>, Yarn will generate a yarn.lock file within the root directory of your package. You don’t need to read or understand this file - just check it into source control. When other people start using Yarn instead of npm, the yarn.lock file will ensure that they get precisely the same dependencies as you have.
