### ISSUE TITLE
ERROR in StatefulButtonModule is not an NgModule

### ISSUE THREAD

**Issue by filipbarak** [interfacewerk/ng2-stateful-button#8]
Hey,

_Sometimes_ when I build the project(``` ng serve ```), this error occurs:
```

ERROR in StatefulButtonModule is not an NgModule
webpack: Failed to compile. 

```

Using angular-cli rc2.0.
Installed it using: npm install ng2-stateful-button --save
It's included like: ``` import {StatefulButtonModule} from 'ng2-stateful-button'; ```
And of course: ``` imports: [StatefulButtonModule] ```
Worth noting: Does not happen every time. Cannot find the cause, any help?

Edit: Added a screenshot of it happening. It fails, but then webpack recompiles itself and the error does not persist.

![screenshot_3](https://cloud.githubusercontent.com/assets/19386836/24610440/d264c59c-187e-11e7-8640-3eeb0af9f996.png)

**Comment by kevinmerckx** [comment]
Hi @filipbarak I will look at it soon and come back to you as soon as I have news for this issue (hopefully a fix :1st_place_medal: )

**Comment by filipbarak** [comment]
Hey @kevinmerckx , thanks. Here's a screenshot of the package.json dependencies I use. Hope it helps.

![screenshot_4](https://cloud.githubusercontent.com/assets/19386836/24615027/6a1d1c6e-188d-11e7-856a-412bd91150e2.png)

**Comment by kevinmerckx** [comment]
@filipbarak the `ng2-stateful-button` will no longer be maintained. HOWEVER, we decided to make it part of a bigger project [https://github.com/interfacewerk/iwerk-angular-ui](https://github.com/interfacewerk/iwerk-angular-ui). Your issue should be fixed there by the way ;)
