### ISSUE TITLE
Attribute selector

### ISSUE THREAD

**Issue by denkomanceski** [interfacewerk/ng2-stateful-button#9]
Isnt it a better approach instead of having the selector 'stateful-button', to actually also have an attribute selector [stateful-button], so we wont have to wrap every button inside <stateful-button> tag, but just add an attribute <button stateful-button [buttonState]='etc'. I dont see any reason for wrapping a button inside a stateful-button.. it some apps it might even break css

**Comment by kevinmerckx** [comment]
Hi @denkomanceski. Thanks for this good feedback. You're completely right in that regard. However, the `ng2-stateful-button` project will no longer be maintained. HOWEVER, it's now part of a bigger project and I already added the issue your reported there ;) [https://github.com/interfacewerk/iwerk-angular-ui/issues/3](https://github.com/interfacewerk/iwerk-angular-ui/issues/3)
